import { CategoryMeta } from "./types";

export const CATEGORIES: CategoryMeta[] = [
  {
    key: "action_required",
    label: "Action Required",
    description: "Emails requiring immediate response or decision",
    emoji: "🔴",
    sortOrder: 1,
    accentColor: "border-accent-red",
    accentBg: "bg-accent-red-bg",
    accentText: "text-accent-red",
  },
  {
    key: "delegate",
    label: "Delegate",
    description: "Tasks suitable for team assignment",
    emoji: "🟡",
    sortOrder: 2,
    accentColor: "border-accent-amber",
    accentBg: "bg-accent-amber-bg",
    accentText: "text-accent-amber",
  },
  {
    key: "fyi",
    label: "FYI",
    description: "Informational updates, no action needed",
    emoji: "🔵",
    sortOrder: 3,
    accentColor: "border-accent-blue",
    accentBg: "bg-accent-blue-bg",
    accentText: "text-accent-blue",
  },
  {
    key: "newsletters",
    label: "Newsletters",
    description: "Industry insights and curated content",
    emoji: "📗",
    sortOrder: 4,
    accentColor: "border-accent-green",
    accentBg: "bg-accent-green-bg",
    accentText: "text-accent-green",
  },
  {
    key: "low_priority",
    label: "Low Priority",
    description: "System notifications and automated updates",
    emoji: "⚪",
    sortOrder: 5,
    accentColor: "border-accent-gray",
    accentBg: "bg-accent-gray-bg",
    accentText: "text-accent-gray",
  },
];
